[package]
name = "http_codex"
version = "1.0.0"
edition = "2021"
description = "A library for easy HTTP code management"
license = "LGPL-3.0-or-later"
repository = "https://github.com/nevermille/http_codex"
authors = ["Camille Nevermind"]

[dependencies]
